FIND_PATH(PCAP_INCLUDE_DIR NAMES pcap/pcap.h pcap.h)
FIND_LIBRARY(PCAP_LIBRARY NAMES pcap)
SET(PCAP_INCLUDE_DIRS ${PCAP_INCLUDE_DIR})
SET(PCAP_LIBRARIES ${PCAP_LIBRARY})

# TODO: check pcap version and functions
MARK_AS_ADVANCED(PCAP_LIBRARIES PCAP_INCLUDE_DIRS)
